version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: datalake-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ./.env
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - nyc_network
  hive-metastore:
    container_name: datalake-hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Access via Thrift protocol
    environment:
      HIVE_METASTORE_DRIVER: ${HIVE_METASTORE_DRIVER}
      HIVE_METASTORE_JDBC_URL: ${HIVE_METASTORE_JDBC_URL}
      HIVE_METASTORE_USER: ${HIVE_METASTORE_USER}
      HIVE_METASTORE_PASSWORD: ${HIVE_METASTORE_PASSWORD}
      # HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/ # HDFS config, we don't need it
      # HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin" # We also don't need it
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      S3_SECRET_KEY: ${MINIO_SECRET_KEY}
      S3_PATH_STYLE_ACCESS: "true"
      # Below arguments exist for no reasons, but
      # we can not live without it
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db
    networks:
      - nyc_network
  metastore_db:
    container_name: datalake-metastore-db
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${HIVE_METASTORE_USER}
      POSTGRES_PASSWORD: ${HIVE_METASTORE_PASSWORD}
      POSTGRES_DB: ${HIVE_POSTGRES_DB}
    volumes:
      - metastore_db_data:/var/lib/postgresql/data
    networks:
      - nyc_network
  trino:
    image: "trinodb/trino:410"
    container_name: datalake-trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro
      - ./trino/catalog/:/etc/trino/catalog
    depends_on:
      - hive-metastore
    networks:
      - nyc_network
  spark-master:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - PYSPARK_PYTHON=python3
    command: ["/opt/spark/sbin/start-master.sh", "-h", "spark-master", "-p", "7077", "--webui-port", "8080"]
    ports:
      - "7077:7077"
      - "8084:8080"
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./spark/conf/fairscheduler.xml:/opt/spark/conf/fairscheduler.xml:ro
      - ./spark/apps:/opt/spark-apps
      - ./spark/logs:/opt/spark/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - nyc_network

  spark-worker-1:
    # image: spark-nyc:latest   # <== dùng image build từ ./spark (tag bạn đặt)
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - PYSPARK_PYTHON=python3
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    depends_on: [spark-master]
    # mem_limit: 4g
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 3g
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./spark/conf/fairscheduler.xml:/opt/spark/conf/fairscheduler.xml:ro
      - ./spark/logs:/opt/spark/logs
    networks: [nyc_network]

  spark-worker-2:
    # image: spark-nyc:latest
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - PYSPARK_PYTHON=python3
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    depends_on: [spark-master]
    # mem_limit: 4g
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 4g
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./spark/conf/fairscheduler.xml:/opt/spark/conf/fairscheduler.xml:ro
      - ./spark/logs:/opt/spark/logs
    networks: [nyc_network]
  
  metabase:
    image: metabase/metabase:latest
    container_name: datalake-metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase.db/metabase.db
    volumes:
      - ./metabase-data:/metabase.db
    depends_on:
      - trino
    networks:
      - nyc_network
  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    entrypoint: /bin/bash
    command: -c "airflow db init && \
                 airflow users create \
                   --username admin \
                   --firstname Air \
                   --lastname Flow \
                   --role Admin \
                   --email admin@example.com \
                   --password admin"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=MJK0tAZlu6zOw8Ibc3oIGuJQb3W25gQmtk3CCn7bm-o=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - nyc_network

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
      - spark-master
      - hive-metastore
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=MJK0tAZlu6zOw8Ibc3oIGuJQb3W25gQmtk3CCn7bm-o=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    command: webserver
    ports:
      - "8089:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      -  /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nyc_network

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - spark-master
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=MJK0tAZlu6zOw8Ibc3oIGuJQb3W25gQmtk3CCn7bm-o=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__PARALLELISM=16
      - AIRFLOW__CORE__DAG_CONCURRENCY=16
      - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=16
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nyc_network

  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - nyc_network

  jupyter:
    build:
      context: ./spark-jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_CONF_DIR=/home/jovyan/spark-conf
      - AWS_ACCESS_KEY_ID= ${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY= ${MINIO_SECRET_KEY}
    volumes:
      - ./spark/conf:/home/jovyan/spark-conf
      - ./spark-jupyter/notebooks:/home/jovyan/notebooks
    depends_on:
      - minio
      - spark-master
    networks:
      - nyc_network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    platform: linux/amd64
    container_name: cdc_zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      retries: 20
      interval: 10s
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nyc_network
  broker:
    image: confluentinc/cp-server:7.5.0
    container_name: cdc_broker
    hostname: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      - nyc_network
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: cdc_schema-registry
    ports:
      - "8081:8081"
    depends_on:
      broker:
        condition: service_healthy
    healthcheck:
      start_period: 10s
      interval: 10s
      retries: 20
      test: curl --user superUser:superUser --fail --silent --insecure http://localhost:8081/subjects --output /dev/null || exit 1
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - nyc_network
  
  debezium:
    image: debezium/connect:1.9
    platform: linux/amd64
    container_name:  cdc_debezium
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '--silent',
          '--fail',
          '-X',
          'GET',
          'http://localhost:8083/connectors',
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8083:8083"
    networks:
      - nyc_network
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      # Set to Avro for higher performance
      # KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      # VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_TOPIC_CREATION_ENABLE: true
  debezium-ui:
    image: debezium/debezium-ui:latest
    platform: linux/amd64
    container_name: cdc_debezium_ui
    ports:
      - "8082:8080"
    hostname: cdc_debezium_ui
    depends_on:
      debezium:
        condition: service_healthy
    networks:
      - nyc_network
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
  postgresql:
    # Set wal_level from replica (default) to logical
    # so that Debezium can capture change
    image: postgres:17
    command: ['postgres', '-c', 'wal_level=logical']
    container_name: cdc_postgresql
    healthcheck:
      test: ['CMD', 'psql', '-U', 'xavie', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=xavie
      - POSTGRES_USER=xavie
      - POSTGRES_PASSWORD=xavie
    networks:
      - nyc_network
    volumes: 
      - cdc_postgres_data:/var/lib/postgresql/data
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    container_name: cdc-control-center
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      debezium:
        condition: service_healthy
    ports:
      - "9021:9021"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9021/healthcheck"] # Adjust the URL and options as needed
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'debezium:8083'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      # How many copies for control-center internal topics
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      # Number of partitions for control-center internal topics
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      # CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      # Health check endpoint to monitor status of connectors
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      # How many copies for confluent metrics topics
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
    networks:
      - nyc_network
volumes:
  minio_storage:
  metastore_db_data:
  airflow_db_data:
  cdc_postgres_data:

networks:
  nyc_network:
    driver: bridge
    name: nyc_network